//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSG_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camere
    {
        public int ID { get; set; }
        public Nullable<int> Capacitate { get; set; }
        public Nullable<int> Pret { get; set; }
    }
}
