//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSG_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerRezervari
    {
        public int ID_USR { get; set; }
        public int ID_CAM { get; set; }
        public System.DateTime Check_in { get; set; }
        public System.DateTime Check_out { get; set; }
        public Nullable<int> Pret_total { get; set; }
    
        public virtual Camere Camere { get; set; }
        public virtual Useri Useri { get; set; }
    }
}
